### ISSUE TITLE
redline-1.2.3 breaks gradle-ospackage-plugin test suite

### ISSUE THREAD

**Issue by sc1478** [craigwblake/redline#109]
Version 1.2.3 is not passing the gradle-ospackage-plugin test suite.  Details are at [https://travis-ci.org/nebula-plugins/gradle-ospackage-plugin/builds/159733276](https://travis-ci.org/nebula-plugins/gradle-ospackage-plugin/builds/159733276) .

This seems to have been caused by this pull request [Feature/multiple dependency support #101](https://github.com/craigwblake/redline/pull/101) .  By returning to a LinkedList implementation of storage, this PR seems to have lost the duplicate-prevention feature that was in version 1.2.2.

**Comment by craigwblake** [comment]
This should be fixed with the PR merged.  I'll get another patch release out as soon as possible.

**Comment by aguther** [comment]
Thank you for fixing!
