### ISSUE TITLE
org.redline_rpm.payload.Directive is not marked as serializable

### ISSUE THREAD

**Issue by vitaliusvs** [craigwblake/redline#133]
I tried to convert build.gradle groovy build (which use gradle-ospackage-plugin and works fine) to build.gradle.kts kotlin build and get
java.io.NotSerializableException: org.redline_rpm.payload.Directive

Related gradle-ospackage-plugin issue: https://github.com/nebula-plugins/gradle-ospackage-plugin/issues/252

**Comment by craigwblake** [comment]
Merged.

**Comment by arkaev** [comment]
Hi! Can we expect new version with this fix?

**Comment by craigwblake-openlaw** [comment]
Thanks for the poke, I'll try to get a new version built in the next day or two.

**Comment by craigwblake** [comment]
Thanks for the poke, I'll try to get a new version built in the next day or two.

**Comment by arkaev** [comment]
Sorry... but again... any news?

**Comment by craigwblake** [comment]
Done.
