### ISSUE TITLE
Is it possible to set the dist Tag with redline?

### ISSUE THREAD

**Issue by renegrob** [craigwblake/redline#79]
Is it possible to set the dist tag (https://fedoraproject.org/wiki/Packaging:DistTag)? There is a "distribution" header tag but this seems to be something different.

**Comment by p120ph37** [comment]
From my reading of Fedora's documentation that you linked, their `%{dist}` tag is not output in the resultant RPM directly.  Rather, it is a macro used during packaging to incorporate the dist string into the "release" header, and also for use in conditionals when you need to generate things differently for different distros.  To emulate this functionality in your use of redline, you can do something like this with Builder:
```java
String dist = ".el6";

builder.setRelease("whatever_base_release"+dist);
if(dist.matches("^\\.el.*$")) {
    // make RHEL-specific adjustments here.
} else if(dist.matches("^\\.fc.*$")) {
    // make Fedora-specific adjustments here.
} // ...etc
```

If you are using the Ant task, you can do similar string-substitution and branching there with a variable as well.

**Comment by renegrob** [comment]
Thanks a lot! I wasn't aware that it's so simple.
