### ISSUE TITLE
ability to extract RPM package contents

### ISSUE THREAD

**Issue by n0mer** [craigwblake/redline#92]
Hi there,

is package contents extraction ability planned?

**Comment by craigwblake** [comment]
I'm not aware of anyone working on this right now, but a patch would be welcome.

**Comment by n0mer** [comment]
`rpm2cpio` did the job for me.

`redline` is nice project, by the way - thank you.

**Comment by craigwblake** [comment]
Glad you were able to find a tool to do this.
